#!/usr/bin/env bash
set -eo pipefail
cd "${0%/*}"

declare LOG_ROOT
declare LICENSE_FILE

declare -r PUBLIC_URL_PREFIX_DEFAULT="http://127.0.0.1:8080"
declare    PUBLIC_URL_PREFIX=${PUBLIC_URL_PREFIX:-$PUBLIC_URL_PREFIX_DEFAULT}

declare -r DEBUG_URL_PREFIX_DEFAULT="http://127.0.0.1:6791"
declare -r DEBUG_URL_PREFIX=${DEBUG_URL_PREFIX:-$DEBUG_URL_PREFIX_DEFAULT}

declare -r GRAFANA_URL_DEFAULT="http://127.0.0.1:3100"
declare -r GRAFANA_URL=${GRAFANA_URL:-$GRAFANA_URL_DEFAULT}

function usage() {
    # TODO :)
    echo "Usage: run-example --license-file <license-file> [options] [cmd]"
    echo "  Options:"
    echo "    --log-root <log-dir> : where on the host to mount Norsk's logs.  The actual logs will be in a subdirectory with the name of the example you are running.  Default ./norskLogs"
if [[ "$OSTYPE" == "linux"* ]]; then
    echo "    --network-mode [docker|host] : whether the example should run in host or docker network mode.  Defaults to host"
fi
    echo "    --metrics [true|false] : whether metrics containers are included. Defaults to false"
    echo "  Commands:"
    echo "    list : List the example names along with a short description of each"
    echo "    start <example-name> : start the named example."
    echo "        The example-name can be full (e.g. 00_hello_norsk), just the number (e.g. 00)"
    echo "        or just the name (e.g. hello_norsk)"
    echo "    stop : Stops the last launched example with \`docker compose down\`"
    echo "    stop-all : Stops all example containers and deletes the associated docker network (if any)"
    echo "  Environment variables:"
    echo "    The run script allows the displayed URLs to have a custom URL root to"
    echo "    facilitate ease of viewing outputs / visualiser / documentation etc."
    echo "    PUBLIC_URL_PREFIX - default: $PUBLIC_URL_PREFIX_DEFAULT"
    echo "    DEBUG_URL_PREFIX - default: $DEBUG_URL_PREFIX_DEFAULT"
    echo
    echo "For example:"
    echo "./run-example --license-file licence.json start rtmp_to_hls"
    echo
}

function dockerComposeCmd() {
    # Earlier version of docker-compose are called differently
    if ! docker compose >/dev/null 2>&1; then
        if ! docker-compose >/dev/null 2>&1; then
            echo ""
        else
            echo "docker-compose"
        fi
    else
        echo "docker compose"
    fi
}

function listExamples() {
    cat docker-compose/host-networking/*yml \
    | grep -e '^#' \
    | sed -e 's/# Norsk Media example: //' \
          -e 's/#/ /' \
          -e '/^[[:space:]]*$/d'
}

function startExample() {
    local -r exampleName=${1}
    local -r ymlPath=${2}
    local -r dockerComposeCmd=$(dockerComposeCmd)
    if [ -z "$dockerComposeCmd" ]; then
        echo "Error: Unable to find docker-compose - exiting"
        exit 1
    fi
    
    pushd "$ymlPath" >/dev/null
    case "$exampleName" in
        [0-9][0-9]) # User gave just the example number
            candidate=$(ls -1 "$1_"*".yml" 2>/dev/null || true | head -1)
        ;;
        [0-9][0-9]_*.yml) # Full match
            candidate=$(ls -1 "$1" 2>/dev/null | head -1)
        ;;
        [0-9][0-9]_*) # Full name of example (no extension)
            candidate=$(ls -1 "$1.yml" 2>/dev/null || true | head -1)
        ;;
        *)
            candidate=$(ls -1 [0-9][0-9]"_$1.yml" 2>/dev/null || true | head -1)
        ;;
    esac
    popd >/dev/null
    
    local -r dcFile="$ymlPath/$candidate"
    if [ ! -f "$dcFile" ]; then
        echo "Error: example not found $exampleName"
        exit 1
    fi
    
    mkdir -p "$LOG_ROOT/$exampleName"
    
    # Different versions of docker-compose treat paths inside yml files differently
    # (some consider paths relative to the yml file - other relative to where you run from)
    # As a result we copy the selected yml file to the current directory with the default
    # docker compose name (docker-compose.yml) so that the behaviour is the same for all
    # all versions. It's also convient for `docker compose down`
    rm -f docker-compose.yml
    cat "$dcFile" |
    sed -e 's#${LICENSE_FILE}#'"$(realpath "$LICENSE_FILE")"'#g' \
        -e 's#${LOG_ROOT}#'"$(realpath "$LOG_ROOT/$exampleName")"'#g' \
    >docker-compose.yml
    echo "$candidate"
    echo "Starting example ${candidate%.*}"
    PUBLIC_URL_PREFIX=$PUBLIC_URL_PREFIX \
    $dockerComposeCmd up --build --detach
    echo "Workflow visualiser URL $DEBUG_URL_PREFIX/visualiser"
    case "$ymlPath" in
        *"metrics")
            echo "Grafana URL $GRAFANA_URL/"
            echo
            ;;
        *)
            ;;
    esac
    echo "Output from example-application (ctrl-c to return to shell - this will not kill the containers!)"
    echo
    docker logs -f norsk-example-app
    echo
    exit 0
}

function stopExample() {
    local -r dockerComposeCmd=$(dockerComposeCmd || exit 1)
    if [ -f docker-compose.yml ]; then
        $dockerComposeCmd down -t 1
    else
        stopAll
    fi
}

function stopAll() {
    local -r matchingContainersCmd='docker ps --all --filter name="^norsk-source" --filter name="^norsk-example" --filter name="norsk-server"'
    local -r matchingNetworksCmd='docker network ls --filter name="^norsk-nw"'
    echo "Stopping the following containers"
    $matchingContainersCmd
    $matchingContainersCmd -q | xargs --no-run-if-empty docker rm -f
    echo
    echo "Deleting the following networks"
    $matchingNetworksCmd
    $matchingNetworksCmd -q | xargs --no-run-if-empty docker network rm
}

function main() {
    local ymlPath
    local dockerComposeCmd
    local addMetrics=false
    
    declare -a positionalArguments
    positionalArguments=()
    
    # Defaults
    if [[ "$OSTYPE" == "linux"* ]]; then
        ymlPath="docker-compose/host-networking"
    else
        ymlPath="docker-compose/docker-networking"
    fi
    LOG_ROOT="norskLogs"
    
    
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h | --help) usage ; exit 0 ;;
            --license-file) export LICENSE_FILE="$2" ; shift 2 ;;
            --log-root) 
                # Remove trailing slash if present
                export LOG_ROOT=${2%/}
                shift 2
            ;;
            --network-mode)
                if [[ "$OSTYPE" == "linux"* ]]; then
                  case "$2" in
                      docker | host) ymlPath="docker-compose/$2-networking" ; shift 2 ;;
                      *) echo "Unknown network-mode $2"; usage ; exit 1 ;;
                  esac
                else
                    echo "network-mode is unsupported on $OSTYPE"; usage ; exit 1
                fi
            ;;
            --metrics)
                case "$2" in
                    true) addMetrics=true ; shift 2 ;;
                    false) addMetrics=false ; shift 2 ;;
                    *) echo "Unknown metrics $2"; usage ; exit 1 ;;
                esac
            ;;
            --) shift ; positionalArguments+=("$@") ; break ;;
            -*) echo "Error: Unknown option $1" ; usage ; exit 1 ;;
            *) positionalArguments+=("$1") ; shift ;;
        esac
    done
    set -- "${positionalArguments[@]}"
    if [[ $# -eq 1 ]]; then
        case "$1" in
            list)
                listExamples
                exit 0
            ;;
            stop)
                stopExample
                exit 0
            ;;
            stop-all)
                stopAll
                exit 0
            ;;
            *)
                echo "Error: Unknown command $1"
                usage
                exit 1
            ;;
        esac
    fi
    
    if [[ -z ${LICENSE_FILE+x} ]]; then
        usage
        exit 1
    fi
    if [[ ! -f ${LICENSE_FILE} ]]; then
        echo "License file not found: ${LICENSE_FILE}"
        exit 1
    fi

    if [[ "$addMetrics" == "true" ]]; then
        ymlPath="$ymlPath"-metrics
    fi

    if [[ $# -eq 2 ]]; then
        case "$1" in
            start)
                echo "Stopping any current example"
                echo
                stopExample
                echo "Starting $2"
                echo
                startExample "$2" "$ymlPath"
            ;;
            *)
                echo "Error: Unknown command $1"
                usage
            ;;
        esac
    fi
}

main "$@"
