{
 "title": "Norsk",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "SRT Connection Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(norsk_connection_count{instance=\"$node\", mediaNodeName=\"SRT TS Source\", nodeName=\"srt_generator\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(norsk_packet_count{instance=\"$node\", mediaNodeName=\"SRT TS Source\", nodeName=\"srt_generator\", type=\"received\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum(norsk_packet_count{instance=\"$node\", mediaNodeName=\"SRT TS Source\", nodeName=\"srt_generator\", type=\"received_lost\"})",
     "legendFormat": "lost"
    },
    {
     "expr": "sum(norsk_packet_count{instance=\"$node\", mediaNodeName=\"SRT TS Source\", nodeName=\"srt_generator\", type=\"retransmitted\"})",
     "legendFormat": "retransmitted"
    }
   ]
  },
  {
   "title": "SRT Stream Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "avg by(mediaType) (rate(norsk_inbound_media_count{instance=\"$node\", mediaNodeName=\"SRT TS Source\", nodeName=\"stream_output_processor\"}[$__rate_interval]))",
     "legendFormat": "{{mediaType}} frame count"
    },
    {
     "expr": "sum by(stream) (norsk_measured_bitrate{instance=\"$node\", mediaNodeName=\"SRT TS Source\", nodeName=\"stream_stats\"})",
     "legendFormat": "{{stream}} bitrate"
    }
   ]
  },
  {
   "title": "SRT Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "norsk_iat_ms{instance=\"$node\", mediaNodeName=\"SRT TS Source\", nodeName=\"stream_output_processor_single_rendition\", label=\"jitter\"}",
     "legendFormat": "{{mediaType}} jitter"
    },
    {
     "expr": "norsk_iat_ms{instance=\"$node\", mediaNodeName=\"SRT TS Source\", nodeName=\"stream_output_processor_single_rendition\", label=\"average\"}",
     "legendFormat": "{{mediaType}} average"
    }
   ]
  },
  {
   "title": "RTMP Connection Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(norsk_connection_count{instance=\"$node\", mediaNodeName=\"RTMP Source\"})",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "RTMP Stream Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "avg by(mediaType) (rate(norsk_inbound_media_count{instance=\"$node\", mediaNodeName=\"RTMP Source\", nodeName=\"stream_output_processor\"}[$__rate_interval]))",
     "legendFormat": "{{mediaType}} frame count"
    },
    {
     "expr": "sum by(stream) (norsk_measured_bitrate{instance=\"$node\", mediaNodeName=\"RTMP Source\", nodeName=\"stream_stats\"})",
     "legendFormat": "{{stream}} bitrate"
    }
   ]
  },
  {
   "title": "RTMP Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "norsk_iat_ms{instance=\"$node\", mediaNodeName=\"RTMP Source\", nodeName=\"stream_output_processor_single_rendition\", label=\"jitter\"}",
     "legendFormat": "{{mediaType}} stddev"
    },
    {
     "expr": "norsk_iat_ms{instance=\"$node\", mediaNodeName=\"RTMP Source\", nodeName=\"stream_output_processor_single_rendition\", label=\"average\"}",
     "legendFormat": "{{mediaType}} average"
    }
   ]
  },
  {
   "title": "WebRTC Output Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by(stream) (norsk_queue_length{instance=\"$node\", mediaNodeId=\"webrtc\", nodeName=\"sync\"})",
     "legendFormat": "{{stream}} sync queue"
    },
    {
     "expr": "sum by(mediaType) (rate(norsk_outbound_media_count{instance=\"$node\", mediaNodeName=\"Local WebRTC\", nodeName=\"stream_input_generator\"}[$__rate_interval]))",
     "legendFormat": "{{mediaType}} frame count"
    }
   ]
  },
  {
   "title": "Message Queue Lens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 16 },
   "targets": [
    { "expr": "norsk_message_queue_len", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{source=\"norsk_erlang\"}"
    }
   ]
  },
  {
   "title": "Message Queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(norsk_message_queue_len)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reductions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "flops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(norsk_reductions[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$node\"}"
    }
   ]
  }
 ]
}