{
 "title": "Norsk Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "MReductions / Sec",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(norsk_reductions[$__rate_interval])) / 1000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Message Queue Length",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(norsk_message_queue_len)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Inbound Connection Counts",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by(mediaNodeClass) (norsk_connection_count{instance=\"$node\"})",
       "legendFormat": "{{mediaNodeClass}}"
      }
     ]
    },
    {
     "title": "Host CPU",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(process_cpu_seconds_total{instance=\"$node\"}[$__interval])) without (kind) * 100",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "Inbound Bitrates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(mediaNodeClass, stream) (norsk_measured_bitrate{instance=\"$node\", mediaNodeType=\"input\"})",
       "legendFormat": "{{mediaNodeClass}} {{stream}}"
      }
     ]
    },
    {
     "title": "Outbound media counts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
     "targets": [
      {
       "expr": "avg by(mediaNodeClass, mediaType) (irate(norsk_outbound_media_count{instance=\"$node\", mediaNodeType!=\"input\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "A/V Sync Queues",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "avg by(mediaNodeClass, stream) (norsk_queue_length{instance=\"$node\", nodeClass=\"sync\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message Queue Lens",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 14 },
     "targets": [
      { "expr": "norsk_message_queue_len", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "SRT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "SRT Connection Stats",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(norsk_packet_count{instance=\"$node\", mediaNodeClass=\"SRT TS Source\", nodeClass=\"srt_generator\", type=\"received\"})",
       "legendFormat": "received"
      },
      {
       "expr": "sum(norsk_packet_count{instance=\"$node\", mediaNodeClass=\"SRT TS Source\", nodeClass=\"srt_generator\", type=\"received_lost\"})",
       "legendFormat": "lost"
      },
      {
       "expr": "sum(norsk_packet_count{instance=\"$node\", mediaNodeClass=\"SRT TS Source\", nodeClass=\"srt_generator\", type=\"retransmitted\"})",
       "legendFormat": "retransmitted"
      }
     ]
    },
    {
     "title": "SRT Stream Stats",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 2 },
     "targets": [
      {
       "expr": "avg by(mediaType) (irate(norsk_inbound_media_count{instance=\"$node\", mediaNodeClass=\"SRT TS Source\", nodeClass=\"stream_output_processor\"}[$__interval]))",
       "legendFormat": "{{mediaType}} frame count"
      },
      {
       "expr": "sum by(stream) (norsk_measured_bitrate{instance=\"$node\", mediaNodeClass=\"SRT TS Source\", nodeClass=\"stream_stats\"})",
       "legendFormat": "{{stream}} bitrate"
      }
     ]
    },
    {
     "title": "SRT IAT",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "norsk_iat_ms{instance=\"$node\", mediaNodeClass=\"SRT TS Source\", nodeClass=\"stream_output_processor_single_rendition\", label=\"jitter\"}",
       "legendFormat": "{{mediaType}} jitter"
      },
      {
       "expr": "norsk_iat_ms{instance=\"$node\", mediaNodeClass=\"SRT TS Source\", nodeClass=\"stream_output_processor_single_rendition\", label=\"average\"}",
       "legendFormat": "{{mediaType}} average"
      }
     ]
    }
   ]
  },
  {
   "title": "RTMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RTMP Stream Stats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "avg by(mediaType) (irate(norsk_inbound_media_count{instance=\"$node\", mediaNodeClass=\"RTMP Source\", nodeClass=\"stream_output_processor\"}[$__interval]))",
       "legendFormat": "{{mediaType}} frame count"
      },
      {
       "expr": "sum by(stream) (norsk_measured_bitrate{instance=\"$node\", mediaNodeClass=\"RTMP Source\", nodeClass=\"stream_stats\"})",
       "legendFormat": "{{stream}} bitrate"
      }
     ]
    },
    {
     "title": "RTMP IAT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "norsk_iat_ms{instance=\"$node\", mediaNodeClass=\"RTMP Source\", nodeClass=\"stream_output_processor_single_rendition\", label=\"jitter\"}",
       "legendFormat": "{{mediaType}} jitter"
      },
      {
       "expr": "norsk_iat_ms{instance=\"$node\", mediaNodeClass=\"RTMP Source\", nodeClass=\"stream_output_processor_single_rendition\", label=\"average\"}",
       "legendFormat": "{{mediaType}} average"
      }
     ]
    }
   ]
  },
  { "title": "WebRTC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "WebRTC Output Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "avg by(stream) (norsk_queue_length{instance=\"$node\", mediaNodeId=\"webrtc\", nodeClass=\"sync\"})",
     "legendFormat": "{{stream}} sync queue"
    },
    {
     "expr": "sum by(mediaType) (rate(norsk_outbound_media_count{instance=\"$node\", mediaNodeClass=\"Local WebRTC\", nodeClass=\"stream_input_generator\"}[$__rate_interval]))",
     "legendFormat": "{{mediaType}} frame count"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{source=\"norsk_erlang\"}"
    }
   ]
  }
 ]
}